spring:
  datasource:
    url: jdbc:mysql://ak46856ei00pl8tg:pzko90g2r34h7ato@lmc8ixkebgaq22lo.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/w7nbyzay5c9r8csm
    username: ak46856ei00pl8tg
    password: pzko90g2r34h7ato
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG