spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG